### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by theusaf** [Czaplicki/mcfunction-support-resources#4]
[Enter steps to reproduce:]

1. Create or open a mcfunction file.
2. Begin typing out a command.

**Atom**: 1.40.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.13.2
**Thrown From**: [mcfunction-support](https://github.com/Czaplicki/mcfunction-support) package 3.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At /Users/tisomadmin/.atom/packages/mcfunction-support/lib/provider.js:292

TypeError: Cannot read property 'startsWith' of undefined
    at Object.getCommandOption (/packages/mcfunction-support/lib/provider.js:292:19)
    at Object.getSuggestions (/packages/mcfunction-support/lib/provider.js:160:46)
    at o.forEach.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:647224)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:646740)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:646478)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:655011)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:656102)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1210649)
    at TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:504418)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:492523)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150)
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39484)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:258055)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:94325)
```

### Commands

```
     -5:48.7.0 core:backspace (input.hidden-input)
  2x -3:43.4.0 autocomplete-plus:confirm (input.hidden-input)
     -3:40.1.0 snippets:expand (atom-text-editor.editor.is-focused)
  3x -3:37.8.0 core:backspace (input.hidden-input)
     -3:25.7.0 editor:newline (input.hidden-input)
  3x -3:23.7.0 core:backspace (input.hidden-input)
     -3:09.7.0 autocomplete-plus:confirm (input.hidden-input)
     -3:08.6.0 snippets:next-tab-stop (input.hidden-input)
     -3:08.6.0 snippets:expand (input.hidden-input)
     -3:08.6.0 editor:indent (input.hidden-input)
  5x -3:06.9.0 core:backspace (input.hidden-input)
     -3:03.6.0 autocomplete-plus:confirm (input.hidden-input)
     -3:03.1.0 snippets:next-tab-stop (input.hidden-input)
     -3:02.5.0 core:move-right (input.hidden-input)
  2x -3:01.9.0 core:backspace (input.hidden-input)
     -0:03.2.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
atom-java-decompiler 0.1.2 
audio 1.5.7 
language-markdown 0.37.0 
mcfunction-lang 1.16.0-20w11a-0 
mcfunction-support 3.4.0 
sort-lines 0.19.0 
svg-preview 0.14.0 
teletype 0.13.4 
```

**Comment by theusaf** [comment]
The issue seems to be with the loot command in `res.json`. Your text editor somehow messed up and leaked its data into the actual code.

You can also enable issues on the main repository in the settings FYI.

**Comment by czaplicki** [comment]
Hi, will look in to it, the loot command was reasently added by a pull, sins I'd stop using atom.

**Comment by theusaf** [comment]
Affects 3.6.0. I'm going to make an issue on the main repo in case you ever decide to start working on this again.
